### ISSUE TITLE
v4 / 개발 TODO

### ISSUE THREAD

**Issue by redgoose-dev** [gooose-eth/slideshow-service#22]
- [x] 대략적인 구상
- [x] db 초기 설계
- [x] 와이어프레임 그리기
- [ ] sql 파일 만들기
- [ ] API 엔드포인트 URL 구성하기
- [ ] 클라이언트 URL 구성하기
- [ ] 프로젝트 기초 구성하기
- [ ] API 개발하기
- [ ] 클라이언트 / UI 퍼블리싱
- [ ] 클라이언트 / API 연동 및 기능작업
