### ISSUE TITLE
프로젝트 기초 구성

### ISSUE THREAD

**Issue by redgoose-dev** [gooose-eth/slideshow-service#29]
- 백엔드는 `bun + express` 조합을 기초로 구성하기
- 프론트엔드는 vue로 구성하기
- 슬라이드쇼 컴포넌트는 별도로 컴포넌트로 만들어져 있다.

## TODO

- [x] express5 와의 시너지가 어떤지 확인해보기
  ㅠㅠ 라우터 부분에서 오류가 발생하지만 리서치하기 시간 많이 걸릴거같아서 4로 바꾸고 진행
- [x] 기초적인 수준으로 프로젝트 구성하기
- [x] sql 파일 만들기
- [x] 인스톨 스크립트 만들기
- [x] 기초적인 API 라우팅과 도구들 구성
